// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://orbxrrrqihwzvpzqacnv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9yYnhycnJxaWh3enZwenFhY252Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIzMDI0OTgsImV4cCI6MjA3Nzg3ODQ5OH0.gh6aKGZGToBNqzMqmlmu8o39AJKZsvcPsYeU9n6oEgI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});