
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xvflgagfwqwfjjrjknby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2ZmxnYWdmd3F3ZmpqcmprbmJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNTk1NDMsImV4cCI6MjA1OTgzNTU0M30.CT6SZhSf5qZBVCWkXz2nwSInmZedtkLmdKp42PQ6_lo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Using any type temporarily until Database types can be properly updated
export const supabase = createClient<any>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Create a function to execute SQL directly
export const executeSQL = async (sql: string): Promise<{ success: boolean; error?: any }> => {
  try {
    const { error } = await supabase.rpc('exec_sql', { query: sql });
    
    if (error) {
      console.error("Error executing SQL:", error);
      return { success: false, error };
    }
    
    return { success: true };
  } catch (error) {
    console.error("Exception executing SQL:", error);
    return { success: false, error };
  }
};

// Create the required SQL functions if they don't exist
const setupSQLFunctions = async () => {
  try {
    console.log("Setting up SQL functions...");
    
    // Check if exec_sql function exists
    const testResult = await supabase.rpc('exec_sql', { 
      query: "SELECT 1 as test" 
    });
    
    if (testResult.error && testResult.error.code === '42883') {
      console.log("Creating exec_sql function...");
      
      // Create exec_sql function using raw REST API call since we can't call a function that doesn't exist yet
      const response = await fetch(`${SUPABASE_URL}/rest/v1/rpc/exec_sql`, {
        method: 'POST',
        headers: {
          'apikey': SUPABASE_PUBLISHABLE_KEY,
          'Content-Type': 'application/json',
          'Prefer': 'return=minimal'
        },
        body: JSON.stringify({
          query: `
            CREATE OR REPLACE FUNCTION exec_sql(query text)
            RETURNS void
            LANGUAGE plpgsql
            SECURITY DEFINER
            AS $$
            BEGIN
              EXECUTE query;
            END;
            $$;
          `
        })
      });
      
      if (!response.ok) {
        const responseText = await response.text();
        console.error("Failed to create exec_sql function:", responseText);
        
        // Try an alternative approach
        console.log("Trying alternative approach to create function...");
        await fetch(`${SUPABASE_URL}/rest/v1/sql`, {
          method: 'POST',
          headers: {
            'apikey': SUPABASE_PUBLISHABLE_KEY,
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({
            query: `
              CREATE OR REPLACE FUNCTION exec_sql(query text)
              RETURNS void
              LANGUAGE plpgsql
              SECURITY DEFINER
              AS $$
              BEGIN
                EXECUTE query;
              END;
              $$;
            `
          })
        });
      } else {
        console.log("exec_sql function created successfully");
      }
    } else {
      console.log("exec_sql function already exists");
    }
  } catch (err) {
    console.error("Error in setupSQLFunctions:", err);
  }
};

// Setup required functions when app loads
(async () => {
  try {
    await setupSQLFunctions();
    console.log("SQL functions setup complete");
  } catch (err) {
    console.error("Error in SQL functions setup:", err);
  }
})();
